title: Hey!This is Shu Wei
description: Key skills <br>Javascript,#AngularJS,#Python,#CSS,#SCSS,#RESTful API
logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
markdown: GFM
