title: Hey!<br>This is Shu Wei
additional_info: Key skills
description: <p>#Javascript,&nbsp;#AngularJS,&nbsp;#Python,&nbsp;#CSS,#SCSS,&nbsp;#RESTful API</p>
logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
markdown: GFM
