title: This is ShuWei
additional_info: Key skills<br>#Javascript,&nbsp;#Angular,&nbsp;#PHP,&nbsp;#Python,&nbsp;#CSS,&nbsp;#SCSS,&nbsp;#RESTful API
description: Open to work.
logo: /assets/img/logo.png
instagram: /assets/img/icons8-instagram.svg
linkedin: /assets/img/icons8-linkedin.svg
ig_url: https://www.instagram.com/theonlyshuwei/
linkedin_url: https://www.linkedin.com/in/shuwei-kuo/
show_downloads: false
theme: jekyll-theme-minimal
markdown: GFM
