title: Hey!This is Shu Wei
description: Key skills <br>#Javascript, <p></p>#AngularJS,&nbsp;#Python,&nbsp;#CSS,#SCSS,&nbsp;#RESTful API
logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
markdown: GFM
