title: Hey!This is Shu Wei
description: Key skills <br> <p>Javascript, #AngularJS, #Python, #CSS, #SCSS, #RESTful API </p>
logo: /assets/img/logo.png
show_downloads: true
theme: jekyll-theme-minimal
markdown: GFM
